# Terraform pipeline
trigger:
- none

pool:
  vmImage: ubuntu-latest
parameters:
  - name: tfApply
    type: boolean
    default: true
    displayName: Apply terraform (if selected)
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
  displayName: Install latest terraform
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Az-connect'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform -chdir=./terraform init
      terraform -chdir=./terraform plan
  displayName: init and plan terrraform 
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Az-connect'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform -chdir=./terraform apply -auto-approve
  displayName: apply terraform 
  condition: and(succeeded(), ${{ eq(parameters.tfApply, true) }})
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Az-connect'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform -chdir=./terraform apply -destroy -auto-approve
  displayName: destroy terraform 
  condition: and(succeeded(), ${{ eq(parameters.tfApply, false) }})
